name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - new-theme

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.0.5
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.JEKYLL_PAT }}
          target_branch: 'gh-pages'